### ISSUE TITLE
Error when building SymEngine, saying that "conda is doing something else"

### ISSUE THREAD

**Issue by Datseris** [symengine/SymEngine.jl#56]
Error message:
```
julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating DifferentialEquations master...
INFO: Updating OrdinaryDiffEq master...
INFO: Updating Plots master...
INFO: Computing changes...
INFO: Installing SymEngine v0.1.2
INFO: Building Conda
INFO: Building SymEngine
Fetching package metadata: ....
Solving package specifications: .........

Package plan for installation in environment C:\Users\migos\.julia\v0.5\SymEngine\deps\usr:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    zlib-1.2.8                 |                0         116 KB

The following NEW packages will be INSTALLED:

    zlib: 1.2.8-0

Fetching packages ...
    LOCKERROR: It looks like conda is already doing something.
    The lock [u'C:\\Users\\migos\\.julia\\v0.5\\Conda\\deps\\usr\\pkgs\\.conda_lock-9344'] was found. Wait for it to finish before continuing.
    If you are sure that conda is not running, remove it and try again.
    You can also use: $ conda clean --lock
Sleeping for 1 seconds
    LOCKERROR: It looks like conda is already doing something.
    The lock [u'C:\\Users\\migos\\.julia\\v0.5\\Conda\\deps\\usr\\pkgs\\.conda_lock-9344'] was found. Wait for it to finish before continuing.
    If you are sure that conda is not running, remove it and try again.
    You can also use: $ conda clean --lock
Sleeping for 2 seconds
    LOCKERROR: It looks like conda is already doing something.
    The lock [u'C:\\Users\\migos\\.julia\\v0.5\\Conda\\deps\\usr\\pkgs\\.conda_lock-9344'] was found. Wait for it to finish before continuing.
    If you are sure that conda is not running, remove it and try again.
    You can also use: $ conda clean --lock
Sleeping for 4 seconds
    LOCKERROR: It looks like conda is already doing something.
    The lock [u'C:\\Users\\migos\\.julia\\v0.5\\Conda\\deps\\usr\\pkgs\\.conda_lock-9344'] was found. Wait for it to finish before continuing.
    If you are sure that conda is not running, remove it and try again.
    You can also use: $ conda clean --lock
Sleeping for 8 seconds
    LOCKERROR: It looks like conda is already doing something.
    The lock [u'C:\\Users\\migos\\.julia\\v0.5\\Conda\\deps\\usr\\pkgs\\.conda_lock-9344'] was found. Wait for it to finish before continuing.
    If you are sure that conda is not running, remove it and try again.
    You can also use: $ conda clean --lock
Sleeping for 16 seconds
    LOCKERROR: It looks like conda is already doing something.
    The lock [u'C:\\Users\\migos\\.julia\\v0.5\\Conda\\deps\\usr\\pkgs\\.conda_lock-9344'] was found. Wait for it to finish before continuing.
    If you are sure that conda is not running, remove it and try again.
    You can also use: $ conda clean --lock
Sleeping for 32 seconds
    LOCKERROR: It looks like conda is already doing something.
    The lock [u'C:\\Users\\migos\\.julia\\v0.5\\Conda\\deps\\usr\\pkgs\\.conda_lock-9344'] was found. Wait for it to finish before continuing.
    If you are sure that conda is not running, remove it and try again.
    You can also use: $ conda clean --lock
Sleeping for 64 seconds
Traceback (most recent call last):
  File "C:\Users\migos\.julia\v0.5\Conda\deps\usr\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\migos\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Users\migos\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Users\migos\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\cli\main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "C:\Users\migos\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\cli\install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\migos\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\migos\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "C:\Users\migos\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\instructions.py", line 52, in FETCH_CMD
    fetch(state['index'], arg)
  File "C:\Users\migos\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\instructions.py", line 48, in fetch
    fetch_pkg(index[fn])
  File "C:\Users\migos\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\fetch.py", line 296, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "C:\Users\migos\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\fetch.py", line 329, in download
    with Locked(dst_dir):
  File "C:\Users\migos\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\lock.py", line 58, in __enter__
    sleep(sleeptime)
KeyboardInterrupt
==================================================[ ERROR: SymEngine ]==================================================

LoadError: InterruptException:
while loading C:\Users\migos\.julia\v0.5\SymEngine\deps\build.jl, in expression starting on line 9

========================================================================================================================
ERROR: InterruptException:
 in process_events(::Bool) at .\libuv.jl:82
 in wait() at .\event.jl:147
 in wait(::Condition) at .\event.jl:27
 in stream_wait(::Base.Process, ::Condition, ::Vararg{Condition,N}) at .\stream.jl:44
 in wait(::Base.Process) at .\process.jl:716
 in build!(::Array{String,1}, ::Dict{Any,Any}, ::Set{Any}) at .\pkg\entry.jl:621
 in build(::Array{String,1}) at .\pkg\entry.jl:641
 in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at .\pkg\entry.jl:557
 in update(::String, ::Set{String}) at .\pkg\entry.jl:458
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#update,Tuple{String,Set{String}}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#update,Tuple{String,Set{String}}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at .\pkg\dir.jl:31
 in update() at .\pkg\pkg.jl:210
```

I can assure you the following two:
1) When this error occurs, there is not instance of python, or any other instance of Julia running.
2) This error is thrown when I do a package update. However, in a what seems a random way, sometimes the error happens, sometimes not... ALL times I do pkg.update, I have no other instance of python or julia running!

**Comment by Datseris** [comment]
Let me also say that this is the first time I have encountered an error that said "conda is doing something else". It hasn't happened to me with any other package so far. (as far as I can remember!)

**Comment by isuruf** [comment]
Can you try below as the error message suggests?
```Julia
using Conda
Conda.runconda(`clean --lock`, "C:\\Users\\migos\\.julia\\v0.6\\SymEngine\\deps\\usr")
```
Lock file is there probably because a Conda command was interrupted or something like that.

**Comment by certik** [comment]
@Datseris sorry about that, I haven't encountered this error either. Let us know if @isuruf's suggestion fixes it.

**Comment by Datseris** [comment]
Tried to run the suggestion, got this:
```
julia> using Conda

julia> Conda.runconda(`clean --lock`, "C:\\Users\\migos\\.julia\\v0.5\\SymEngine\\deps\\usr")
ERROR: ArgumentError: Path to conda environment is not valid.
 in prefix at C:\Users\migos\.julia\v0.5\Conda\src\Conda.jl:60 [inlined]
 in _install_conda(::String, ::Bool) at C:\Users\migos\.julia\v0.5\Conda\src\Conda.jl:202
 in runconda(::Cmd, ::String) at C:\Users\migos\.julia\v0.5\Conda\src\Conda.jl:130
```

**Comment by isuruf** [comment]
Sorry, that should have been just
```Julia
using Conda
Conda.runconda(`clean --lock`)
```

**Comment by Datseris** [comment]
So, here is the thing. When I do my first package update, I get the error I describe in this post. After that, if I do again update, nothing goes wrong.
During this second update attempt, when nothing goes wrong, I tried the command:
```
julia> Conda.runconda(`clean --lock`)
removing: C:\Users\migos\.julia\v0.5\Conda\deps\usr\pkgs\.conda_lock-9344
```

But I don't know what to do now

**Comment by isuruf** [comment]
If nothing goes wrong on the second attempt, does `using SymEngine` work?

**Comment by Datseris** [comment]
Yes, it does work. There are no errors at least when `using SymEngine`, but I don't know any commands to run to see if it *really* works.

**Comment by isuruf** [comment]
`Pkg.test("SymEngine")` will test the package

**Comment by Datseris** [comment]
```
julia> Pkg.test("SymEngine")
INFO: Testing SymEngine
ERROR: LoadError: LoadError: error compiling _symbol: error compiling _symbol: could not load library "symengine"
The specified module could not be found.

 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in process_options(::Base.JLOptions) at .\client.jl:262
 in _start() at .\client.jl:318
while loading C:\Users\migos\.julia\v0.5\SymEngine\test\test-dense-matrix.jl, in expression starting on line 5
while loading C:\Users\migos\.julia\v0.5\SymEngine\test\runtests.jl, in expression starting on line 4
==================================================[ ERROR: SymEngine ]==================================================

failed process: Process(`'C:\Users\migos\AppData\Local\Julia-0.5.0\bin\julia' -Cx86-64 '-JC:\Users\migos\AppData\Local\Julia-0.5.0\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes 'C:\Users\migos\.julia\v0.5\SymEngine\test\runtests.jl'`, ProcessExited(1)) [1]

========================================================================================================================
ERROR: SymEngine had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at .\pkg\entry.jl:740
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at .\<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\pkg\dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258
 in test(::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258
```

**Comment by ChrisRackauckas** [comment]
You have ParameterizedFunctions, so just give the repo example a go:

```julia
f = @ode_def LotkaVolterra begin
  dx = a*x - b*x*y
  dy = -c*y + d*x*y
end a=>1.5 b=>1 c=3 d=1
```

It should build everything but throw a warning that it cannot invert the Hessian (which is mathematically correct)

**Comment by Datseris** [comment]
Nope, not even that:
```
julia> f = @ode_def LotkaVolterra begin
         dx = a*x - b*x*y
         dy = -c*y + d*x*y
       end a=>1.5 b=>1 c=3 d=1
ERROR: error compiling #ode_def_opts#1: error compiling symbolize: error compiling symbols: error compiling _symbol: could not load library "symengine"
The specified module could not be found.

 in ode_def_opts(::Symbol, ::Dict{Symbol,Bool}, ::Expr, ::Expr, ::Vararg{Expr,N}) at C:\Users\migos\.julia\v0.5\ParameterizedFunctions\src\ode_def_opts.jl:5
```

**Comment by musm** [comment]
I get problem  on windows with this package. can we please not redownload all of conda if it is already installed. Please something like PyPlots where it uses the system conda installation.

**Comment by isuruf** [comment]
@musm, `Conda.jl` can be configured to use a system conda installation. https://github.com/JuliaPy/Conda.jl#using-an-already-existing-conda-installation

**Comment by ChrisRackauckas** [comment]
This issue could probably be closed, right?

**Comment by ChrisRackauckas** [comment]
Bumping the closing? I thought @Datseris 's problems were fixed.

**Comment by isuruf** [comment]
Right, now that we are not using Conda on windows, this should be fixed

**Comment by Datseris** [comment]
Right now I don't have any problems, that is true. `Pkg.update()` works fine (it does that REALLY weird thing where it installs a huge amount of stuff everytime).
